self.conn = sqlite3.connect(db_path, check_same_thread=False)
self.c = self.conn.cursor()
self.c.execute("CREATE TABLE IF NOT EXISTS memory (role TEXT, content TEXT)")
self.conn = sqlite3.connect(db_path, check_same_thread=False)
self.c = self.conn.cursor()
self.c.execute("CREATE TABLE IF NOT EXISTS memory (role TEXT, content TEXT)")
self.conn = sqlite3.connect(db_path, check_same_thread=False)
self.c = self.conn.cursor()
self.c.execute("CREATE TABLE IF NOT EXISTS memory (role TEXT, content TEXT)")